import { useEffect, useState } from 'react';
import axios from 'axios';
import {
  Table,
  TableBody,
  TableCell,
  TableRow,
  TableHead,
  Button,
  TextField,
  MenuItem,
  Paper,
  Typography,
  Box
} from '@mui/material';
import jsPDF from "jspdf";

const API = "https://nirmalani-payroll-production.up.railway.app";

export default function Payslips({
  plantation
}) {
  const [data, setData] = useState([]);
  const [month, setMonth] = useState("");

  useEffect(() => {
    if (month) {
      axios.get(`${API}/payroll/${month}?plantation=${plantation}`)
        .then(res => setData(res.data));
    } else {
      axios.get(`${API}/payroll?plantation=${plantation}`)
        .then(res => setData(res.data));
    }
  }, [month]);

  const formatMemberId = (id) => {
    return String(id).padStart(6, '0');
  };

  // CALCULATION
const calculate = (salary, allowance = 0) => {
  const basicSalary =
    Number(salary || 0);
  const allowanceAmount =
    Number(allowance || 0);
  const epf_8 =
    basicSalary * 0.08;
  const epf_12 =
    basicSalary * 0.12;
  const epf_20 =
    epf_8 + epf_12;
  const etf =
    basicSalary * 0.03;
  const deduction =
    epf_8;
  const netSalary =
    basicSalary -
    deduction +
    allowanceAmount;
  return {
    amount: basicSalary,
    epf_8,
    epf_12,
    epf_20,
    etf,
    deduction,
    allowance: allowanceAmount,
    netSalary
  };
};

  // GENERATE EMPLOYEE PAYSLIP
  const generatePayslip = (emp) => {
    try {
      const doc = new jsPDF();

      const green = [34, 139, 34];

      // HEADER
      doc.setFillColor(...green);
      doc.rect(0, 0, 210, 25, "F");

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(16);
      doc.text("NIRMALANI PLANTATION 🌿", 14, 15);

      doc.setFontSize(10);
      doc.text("Employee Payslip", 150, 15);

      doc.setTextColor(0, 0, 0);

      // EMPLOYEE BOX
      doc.setDrawColor(200);
      doc.rect(10, 35, 190, 45);

      doc.setFontSize(12);
      doc.text(`Name: ${emp.name}`, 15, 45);
      doc.text(`Member ID: ${formatMemberId(emp.memberid)}`, 15, 55);
      doc.text(`Month: ${emp.month || "-"}`, 15, 65);

      // SALARY SECTION
      let y = 90;

      doc.setFontSize(14);
      doc.setTextColor(...green);
      doc.text("Earnings", 15, y);

      doc.setTextColor(0, 0, 0);
      y += 10;

      const row = (label, value) => {
        doc.text(label, 20, y);
        doc.text(String(value), 170, y, { align: "right" });
        y += 10;
      };

      const epf = emp.epf || (emp.basic_salary * 0.08).toFixed(2);

      row("Basic Salary", `Rs. ${emp.basic_salary}`);
      row("Allowance", `Rs. ${emp.total_allowance}`);

      y += 5;

      doc.setTextColor(200, 0, 0);
      doc.text("Deductions", 15, y);

      doc.setTextColor(0, 0, 0);
      y += 10;

      row("EPF (8%)", `Rs. ${epf}`);

      // NET SALARY BOX
      y += 10;
      doc.setFillColor(220, 255, 220);
      doc.rect(10, y - 8, 190, 12, "F");

      doc.setFontSize(13);
      doc.setTextColor(0, 100, 0);
      doc.text("Net Salary", 20, y);
      doc.text(`Rs. ${emp.net_salary}`, 170, y, { align: "right" });

      // FOOTER
      doc.setTextColor(100);
      doc.setFontSize(10);
      doc.text("Generated by Nirmalani Payroll System", 60, 280);
      doc.text("Authorized Signature: ____________________", 20, 260);

      // DOWNLOAD
      doc.save(`${emp.name}_Payslip.pdf`);

    } catch (err) {
      console.error("PDF ERROR:", err);
      alert("PDF generation failed");
    }
  };

  const printMonthlyReport = () => {

    if (!month) {
      alert("Select month");
      return;
    }

    const rows = data;

    const totals = {
      amount: 0,
      epf_8: 0,
      deduction: 0,
      epf_12: 0,
      epf_20: 0,
      etf: 0,
      allowance: 0,
      netSalary: 0
    };

    const rowsHTML = rows.map((emp) => {

      const c = calculate(
        emp.basic_salary,
        emp.total_allowance
      );

      totals.amount += c.amount;
      totals.epf_8 += c.epf_8;
      totals.deduction += c.deduction;
      totals.epf_12 += c.epf_12;
      totals.epf_20 += c.epf_20;
      totals.etf += c.etf;
      totals.allowance += Number(emp.total_allowance || 0);
      totals.netSalary += c.netSalary;

      return `
        <tr>
          <td>${emp.name}</td>
          <td>${formatMemberId(emp.memberid)}</td>
          <td>${emp.month}</td>
          <td>${c.amount.toFixed(2)}</td>
          <td>${c.epf_8.toFixed(2)}</td>
          <td>${c.deduction.toFixed(2)}</td>
          <td>${c.epf_12.toFixed(2)}</td>
          <td>${c.epf_20.toFixed(2)}</td>
          <td>${c.etf.toFixed(2)}</td>
          <td>${emp.total_allowance || 0}</td>
          <td>${c.netSalary.toFixed(2)}</td>

        </tr>
      `;
    }).join("");

    const html = `
      <html>

      <head>

        <title>Monthly Payroll Report</title>

        <style>

          body{
            font-family:Arial;
            padding:20px;
          }

          table{
            width:100%;
            border-collapse:collapse;
          }

          th,td{
            border:1px solid #000;
            padding:8px;
          }

        </style>

      </head>

      <body>

        <h2>Nirmalani Plantation</h2>

        <h3>
          Employee Monthly Payroll Report
        </h3>

        <h3>
          Month : ${month}
        </h3>

        <table>

          <tr>

            <th>Name</th>
            <th>Member ID</th>
            <th>Month</th>
            <th>Amount</th>
            <th>EPF 8%</th>
            <th>Deduction</th>
            <th>EPF 12%</th>
            <th>EPF 20%</th>
            <th>ETF</th>
            <th>Allowance</th>
            <th>Net Salary</th>

          </tr>

          ${rowsHTML}

          <tr style="font-weight:bold; background:#f1f5f9">

            <td colspan="3">
              TOTAL
            </td>
            <td>${totals.amount.toFixed(2)}</td>
            <td>${totals.epf_8.toFixed(2)}</td>
            <td>${totals.deduction.toFixed(2)}</td>
            <td>${totals.epf_12.toFixed(2)}</td>
            <td>${totals.epf_20.toFixed(2)}</td>
            <td>${totals.etf.toFixed(2)}</td>
            <td>${totals.allowance.toFixed(2)}</td>
            <td>${totals.netSalary.toFixed(2)}</td>

          </tr>

        </table>

        <script>
          window.print();
        </script>

      </body>

      </html>
    `;

    const win = window.open("", "_blank");

    win.document.write(html);

    win.document.close();
  };

  const filteredData = month
    ? data.filter(emp => emp.month === month)
    : data;

const totals = filteredData.reduce(
  (acc, emp) => {

    const c = calculate(
      emp.basic_salary,
      emp.total_allowance
    );

    acc.amount += c.amount;
    acc.epf_8 += c.epf_8;
    acc.deduction += c.deduction;
    acc.epf_12 += c.epf_12;
    acc.epf_20 += c.epf_20;
    acc.etf += c.etf;
    acc.allowance += Number(
      emp.total_allowance || 0
    );
    acc.netSalary += c.netSalary;

    return acc;
  },
  {
    amount: 0,
    epf_8: 0,
    deduction: 0,
    epf_12: 0,
    epf_20: 0,
    etf: 0,
    allowance: 0,
    netSalary: 0
  }
);

const totalMoneyRequired =
  totals.netSalary +
  totals.epf_20 +
  totals.etf;

  return (
    <Box sx={{
      p: 3,
      minHeight: "100vh",
      background: "linear-gradient(135deg, #0f172a, #1e293b)"
    }}>

      <Typography variant="h4" sx={{
        mb: 3,
        color: "#fff",
        fontWeight: 800
      }}>
        🧾 Payslips
      </Typography>

      {/* FILTER */}
      <Paper sx={{
        p: 3,
        mb: 3,
        borderRadius: 5,
        background: "rgba(255,255,255,0.05)"
      }}>
        <TextField
          select
          label="Select Month"
          value={month}
          onChange={(e) => setMonth(e.target.value)}
          sx={{ width: 220 }}
        >
          <MenuItem value="">All Months</MenuItem>
          {[
            "January","February","March","April","May","June",
            "July","August","September","October","November","December"
          ].map(m => (
            <MenuItem key={m} value={m}>{m}</MenuItem>
          ))}
        </TextField>

        <Button
          onClick={printMonthlyReport}
          sx={{
            ml: 2,
            background: "#a855f7",
            color: "#fff",
            height: "56px",
            fontWeight: "bold"
          }}
        >
          MONTHLY REPORT
        </Button>

        <Box
          sx={{
            mt: 3,
            display: "grid",
            gridTemplateColumns:
              "repeat(auto-fit,minmax(220px,1fr))",
            gap: 3,
            mb: 3
          }}
        >

          <Paper
            sx={{
              p: 3,
              background: "#1e3a8a",
              color: "#fff",
              borderRadius: 4
            }}
          >
            <Typography variant="h6">
              💵 Net Salary
            </Typography>

            <Typography
              variant="h5"
              fontWeight="bold"
            >
              Rs. {totals.netSalary.toFixed(2)}
            </Typography>
          </Paper>

          <Paper
            sx={{
              p: 3,
              background: "#166534",
              color: "#fff",
              borderRadius: 4
            }}
          >
            <Typography variant="h6">
              🏦 EPF 20%
            </Typography>

            <Typography
              variant="h5"
              fontWeight="bold"
            >
              Rs. {totals.epf_20.toFixed(2)}
            </Typography>
          </Paper>

          <Paper
            sx={{
              p: 3,
              background: "#92400e",
              color: "#fff",
              borderRadius: 4
            }}
          >
            <Typography variant="h6">
              📄 ETF
            </Typography>

            <Typography
              variant="h5"
              fontWeight="bold"
            >
              Rs. {totals.etf.toFixed(2)}
            </Typography>
          </Paper>

          <Paper
            sx={{
              p: 3,
              background: "#14532d",
              color: "#fff",
              borderRadius: 4
            }}
          >
            <Typography variant="h6">
              💰 Total Required
            </Typography>

            <Typography
              variant="h4"
              fontWeight="bold"
            >
              Rs. {totalMoneyRequired.toFixed(2)}
            </Typography>
          </Paper>

        </Box>
      </Paper>

      {/* TABLE */}
      <Paper sx={{
        p: 2,
        borderRadius: 5,
        background: "rgba(255,255,255,0.05)"
      }}>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell sx={{ color: "#aaa" }}>Name</TableCell>
              <TableCell sx={{ color: "#aaa" }}>Member ID</TableCell>
              <TableCell sx={{ color: "#aaa" }}>Month</TableCell>
              <TableCell sx={{ color: "#aaa" }}>Amount</TableCell>
              <TableCell sx={{ color: "#aaa" }}>EPF 8%</TableCell>
              <TableCell sx={{ color: "#aaa" }}>Deduction</TableCell>
              <TableCell sx={{ color: "#aaa" }}>EPF 12%</TableCell>
              <TableCell sx={{ color: "#aaa" }}>EPF 20%</TableCell>
              <TableCell sx={{ color: "#aaa" }}>ETF</TableCell>
              <TableCell sx={{ color: "#aaa" }}>Allowance</TableCell>
              <TableCell sx={{ color: "#aaa" }}>Net Salary</TableCell>
              <TableCell sx={{ color: "#aaa" }}>Action</TableCell>
            </TableRow>
          </TableHead>

          <TableBody>

            {data.length > 0 ? (

              data.map((emp, index) => {

                const c = calculate(
                  emp.basic_salary,
                  emp.total_allowance
                );

                return (

                  <TableRow key={index}>

                    <TableCell sx={{ color: "#fff" }}>
                      {emp.name}
                    </TableCell>

                    <TableCell sx={{ color: "#fff" }}>
                      {formatMemberId(emp.memberid)}
                    </TableCell>

                    <TableCell sx={{ color: "#fff" }}>
                      {emp.month}
                    </TableCell>

                    <TableCell sx={{ color: "#22c55e" }}>
                      {c.amount.toFixed(2)}
                    </TableCell>

                    <TableCell sx={{ color: "#facc15" }}>
                      {c.epf_8.toFixed(2)}
                    </TableCell>

                    <TableCell sx={{ color: "#f87171" }}>
                      {c.deduction.toFixed(2)}
                    </TableCell>

                    <TableCell sx={{ color: "#a78bfa" }}>
                      {c.epf_12.toFixed(2)}
                    </TableCell>

                    <TableCell sx={{ color: "#fb7185" }}>
                      {c.epf_20.toFixed(2)}
                    </TableCell>

                    <TableCell sx={{ color: "#34d399" }}>
                      {c.etf.toFixed(2)}
                    </TableCell>

                    <TableCell sx={{ color: "#14b8a6" }}>
                      {emp.total_allowance}
                    </TableCell>

                    <TableCell sx={{ color: "#38bdf8", fontWeight: 700 }}>
                      {c.netSalary.toFixed(2)}
                    </TableCell>

                    <TableCell>

                      <Button
                        onClick={() => generatePayslip(emp)}
                        sx={{
                          background: "#16a34a",
                          color: "#fff",
                          fontWeight: "bold"
                        }}
                      >
                        PDF
                      </Button>

                    </TableCell>

                  </TableRow>

                );

              })

            ) : (

              <TableRow>

                <TableCell
                  colSpan={12}
                  sx={{ color: "#aaa" }}
                >
                  No data available
                </TableCell>

              </TableRow>

            )}
            <TableRow
              sx={{
                background: "rgba(255,255,255,0.08)"
              }}
            >

              <TableCell
                colSpan={3}
                sx={{
                  color: "#fff",
                  fontWeight: "bold"
                }}
              >
                TOTAL
              </TableCell>

              <TableCell sx={{ color: "#22c55e", fontWeight: "bold" }}>
                {totals.amount.toFixed(2)}
              </TableCell>

              <TableCell sx={{ color: "#facc15", fontWeight: "bold" }}>
                {totals.epf_8.toFixed(2)}
              </TableCell>

              <TableCell sx={{ color: "#f87171", fontWeight: "bold" }}>
                {totals.deduction.toFixed(2)}
              </TableCell>

              <TableCell sx={{ color: "#a78bfa", fontWeight: "bold" }}>
                {totals.epf_12.toFixed(2)}
              </TableCell>

              <TableCell sx={{ color: "#fb7185", fontWeight: "bold" }}>
                {totals.epf_20.toFixed(2)}
              </TableCell>

              <TableCell sx={{ color: "#34d399", fontWeight: "bold" }}>
                {totals.etf.toFixed(2)}
              </TableCell>

              <TableCell sx={{ color: "#14b8a6", fontWeight: "bold" }}>
                {totals.allowance.toFixed(2)}
              </TableCell>

              <TableCell sx={{ color: "#38bdf8", fontWeight: "bold" }}>
                {totals.netSalary.toFixed(2)}
              </TableCell>

              <TableCell />
            </TableRow>

          </TableBody>
        </Table>
      </Paper>

    </Box>
  );
}