import { useEffect, useState } from 'react';
import axios from 'axios';
import {
  Table,
  TableBody,
  TableCell,
  TableRow,
  TableHead,
  Button,
  TextField,
  MenuItem,
  Paper,
  Typography,
  Box
} from '@mui/material';
import jsPDF from "jspdf";

const API = "https://nirmalani-payroll-production.up.railway.app";

export default function Payslips() {
  const [data, setData] = useState([]);
  const [month, setMonth] = useState("");

  useEffect(() => {
    if (month) {
      axios.get(`${API}/payroll/${month}`)
        .then(res => setData(res.data));
    } else {
      axios.get(`${API}/payroll`)
        .then(res => setData(res.data));
    }
  }, [month]);

  const formatMemberId = (id) => {
    return String(id).padStart(6, '0');
  };

  // 🌿 PROFESSIONAL CINNAMON PAYSLIP DESIGN
  const generatePayslip = (emp) => {
    try {
      const doc = new jsPDF();

      const green = [34, 139, 34];

      // HEADER
      doc.setFillColor(...green);
      doc.rect(0, 0, 210, 25, "F");

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(16);
      doc.text("NIRMALANI PLANTATION 🌿", 14, 15);

      doc.setFontSize(10);
      doc.text("Employee Payslip", 150, 15);

      doc.setTextColor(0, 0, 0);

      // EMPLOYEE BOX
      doc.setDrawColor(200);
      doc.rect(10, 35, 190, 40);

      doc.setFontSize(12);
      doc.text(`Name: ${emp.name}`, 15, 45);
      doc.text(`Member ID: ${formatMemberId(emp.memberid)}`, 15, 55);
      doc.text(`Month: ${emp.month || "-"}`, 15, 65);

      // SALARY SECTION
      let y = 90;

      doc.setFontSize(14);
      doc.setTextColor(...green);
      doc.text("Earnings", 15, y);

      doc.setTextColor(0, 0, 0);
      y += 10;

      const row = (label, value) => {
        doc.text(label, 20, y);
        doc.text(String(value), 170, y, { align: "right" });
        y += 10;
      };

      const epf = emp.epf || (emp.basic_salary * 0.08).toFixed(2);

      row("Basic Salary", `Rs. ${emp.basic_salary}`);
      row("Allowance", `Rs. ${emp.total_allowance}`);

      y += 5;

      doc.setTextColor(200, 0, 0);
      doc.text("Deductions", 15, y);

      doc.setTextColor(0, 0, 0);
      y += 10;

      row("EPF (8%)", `Rs. ${epf}`);

      // NET SALARY BOX
      y += 10;
      doc.setFillColor(220, 255, 220);
      doc.rect(10, y - 8, 190, 12, "F");

      doc.setFontSize(13);
      doc.setTextColor(0, 100, 0);
      doc.text("Net Salary", 20, y);
      doc.text(`Rs. ${emp.net_salary}`, 170, y, { align: "right" });

      // FOOTER
      doc.setTextColor(100);
      doc.setFontSize(10);
      doc.text("Generated by Nirmalani Payroll System", 60, 280);
      doc.text("Authorized Signature: ____________________", 20, 260);

      // DOWNLOAD
      doc.save(`${emp.name}_Payslip.pdf`);

    } catch (err) {
      console.error("PDF ERROR:", err);
      alert("PDF generation failed");
    }
  };

  return (
    <Box sx={{
      p: 3,
      minHeight: "100vh",
      background: "linear-gradient(135deg, #0f172a, #1e293b)"
    }}>

      <Typography variant="h4" sx={{
        mb: 3,
        color: "#fff",
        fontWeight: 800
      }}>
        🧾 Payslips
      </Typography>

      {/* FILTER */}
      <Paper sx={{
        p: 3,
        mb: 3,
        borderRadius: 5,
        background: "rgba(255,255,255,0.05)"
      }}>
        <TextField
          select
          label="Select Month"
          value={month}
          onChange={(e) => setMonth(e.target.value)}
          sx={{ width: 220 }}
        >
          <MenuItem value="">All Months</MenuItem>
          {[
            "January","February","March","April","May","June",
            "July","August","September","October","November","December"
          ].map(m => (
            <MenuItem key={m} value={m}>{m}</MenuItem>
          ))}
        </TextField>
      </Paper>

      {/* TABLE */}
      <Paper sx={{
        p: 2,
        borderRadius: 5,
        background: "rgba(255,255,255,0.05)"
      }}>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell sx={{ color: "#aaa" }}>Name</TableCell>
              <TableCell sx={{ color: "#aaa" }}>Member ID</TableCell>
              <TableCell sx={{ color: "#aaa" }}>Month</TableCell>
              <TableCell sx={{ color: "#aaa" }}>Days</TableCell>
              <TableCell sx={{ color: "#aaa" }}>Allowance</TableCell>
              <TableCell sx={{ color: "#aaa" }}>Net Salary</TableCell>
              <TableCell sx={{ color: "#aaa" }}>Action</TableCell>
            </TableRow>
          </TableHead>

          <TableBody>
            {data.length > 0 ? (
              data.map((emp, index) => (
                <TableRow key={index}>
                  <TableCell sx={{ color: "#fff" }}>{emp.name}</TableCell>
                  <TableCell sx={{ color: "#fff" }}>
                    {formatMemberId(emp.memberid)}
                  </TableCell>
                  <TableCell sx={{ color: "#fff" }}>{emp.month}</TableCell>
                  <TableCell sx={{ color: "#fff" }}>{emp.days_worked}</TableCell>
                  <TableCell sx={{ color: "#f59e0b" }}>
                    Rs. {emp.total_allowance}
                  </TableCell>
                  <TableCell sx={{ color: "#22c55e", fontWeight: 700 }}>
                    Rs. {emp.net_salary}
                  </TableCell>

                  <TableCell>
                    <Button
                      onClick={() => generatePayslip(emp)}
                      sx={{
                        background: "#16a34a",
                        color: "#fff"
                      }}
                    >
                      PDF
                    </Button>
                  </TableCell>

                </TableRow>
              ))
            ) : (
              <TableRow>
                <TableCell colSpan={7} sx={{ color: "#aaa" }}>
                  No data available
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </Paper>

    </Box>
  );
}